remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: [Praveen Varukolu]
description: [Currently working as Senior Manager-Data Analytics with IT team in Poonawalla Fincorp, located in Pune. Versatile, results-driven professional with 5 years of comprehensive experience in driving Data Analytics and IT projects to deliver actionable insights and cost benefits.]
